development:
  adapter: postgresql
  encoding: unicode
  database: Motoprieks_development
  pool: 5
  username: blog
  password: ruby

test:
  adapter: postgresql
  encoding: unicode
  database: Motoprieks_test
  pool: 5
  username: blog
  password: ruby

production:
  adapter: postgresql
  encoding: unicode
  database: Motoprieks_production
  pool: 5
  username: blog
  password: ruby
